#!/bin/bash

#Check if sudo
if [ "$EUID" -ne 0 ]
	then echo "Please run as root"
	exit
fi

pacman -Sy --noconfirm

pip install ttkthemes --break-system-packages

git clone https://github.com/xk-rl/ArchCodeInstall
cd ArchCodeInstall
python3 installer.py
